 # -*- mode: ruby -*-
 # vi: set ft=ruby :

 Vagrant.configure(2) do |config|
   config.vm.box = "bento/centos-7.3"

   config.vm.define "gpdb" do |node|
     node.vm.hostname = "gpdb.gpdb.local"
     node.vm.network "private_network", ip: "192.168.33.10", name: "vboxnet1"
     node.vm.provider "virtualbox" do |vb|
       vb.name = "gpdb"
       vb.memory = "2048"
     end
   end

   #config.vm.provision "shell", inline: <<-SHELL
   #   sudo /bin/bash /vagrant/sys_prep.sh
   #SHELL

   #config.vm.provision "shell", path => 'sys_prep.sh', env:{"API_KEY" => "Ignacio"}

   api_key = "YOURAPIKEY"
   config.vm.provision :shell, :path => 'sys_prep.sh', :args => [api_key]

 end
