# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
    config.vm.box = "bento/centos-7.4"

    config.vm.define "gpdb" do |node|
        node.vm.hostname = "gpdb"
        node.vm.network "private_network", ip: "192.168.11.10", name: "vboxnet1"
        node.vm.provider "virtualbox" do |vb|
            vb.name = "gpdb"
            vb.memory = "8196"
        end
   end

   api_key = "APIKEY"
   config.vm.provision :shell, :path => 'sys_prep.sh', :args => [api_key]

end
